services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-mysql-init:/docker-entrypoint-initdb.d # Mount initialization script
    command: --init-file /docker-entrypoint-initdb.d/init.sql

  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
    command: sh -c "npm i typescript -g && npm i typeorm -g && npm run migration:run && npm run start"

volumes:
  mysql_data:
    driver: local
