services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DB: todo
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
    driver: local
